[project]
name = "rw-rate-all"
version = "2024.1"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "ruff>=0.14.8",
    "ty>=0.0.1a33",
]
